# Create a VPC
AWS-VPC = "MY-VPC"

# Create Public Subnets
AWS-PUB-SUB-01 = "PUB-SUB-1a"
AWS-PUB-SUB-02 = "PUB-SUB-1b"

# 2. Create 2 Private Subnets
AWS-PRI-SUB-01 = "PRI-SUB-1a"
AWS-PRI-SUB-02 = "PRI-SUB-1b"

# 3. Create IGW (Internet Gateway) & Attach to the VPC
AWS-IGW = "MY-INTERNET-GW"

# 4. Create Public and Private Route Table
AWS-PUB-ROUTE = "Public-Route"
AWS-PRI-ROUTE = "Private-Route"
#EC2 INSTANCE
AWS-INST-IMG-ID = "ami-00952f27cf14db9cd"
AWS-INST-TYPE   = "t2.micro"
AWS-INST-NAME   = "HELLO-ASFIA"
ASSOC-PUB-IP    = true

#SSH KEY-PAIR 
AWS-KEY-NAME = "TEAM-KEY"
AWS-PUB-KEY  = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbfBiOWAXVijUydGADDc/Oa00P52YXy138A6pcPp82Jf3nH9raccAMklf+SiwFRJoDD+CF4paZqGqLIV5Bk1O7Rw1CS2tjOAWvBZkhDIRfwZvivttKonk1ymThLqOyFco5oCi9/BJ6uaTH3+acu6ZeKjJBr6GrRaA0P+16KAX58nUZpYmhvqj7RY/0+kZcErBQvERI8bkkpWv8PMdyvZDkFKYUdnBYFP3TdPjk4HwYB1Cq7ILS2lE1cjDLYTgKQAbtYNOrMSPfyNZDVJwJ4uQilcw4Qyd8fnrkiYE1JEHaCi5RZr5b2IV4+3t16p9EAtzjj7aIFu2UNKmA9RgRjmljs5QhxesR1mIw17l6YWEVlPS9ohy2EhaFbThhKFXsFW0i8C6+OT3vfKAy56P5mNpHOfaA25Nan3b1V70q9prxF7JIN9yOrUGn7BY6EmthncGvkKEmAlvGubkbVp6nnonD9tjmM0LTOzGulyo2zhzBIFG+rrd5F94JG4WkEw0Veis="

#SSH SECURITY GROUP
AWS-SG-NAME    = "TEAM-SG"
AWS-SG-DESC    = "TEAM-SG"
AWS-SG-PORT    = [22, 80, 443]
AWS-SG-PROTO   = "tcp"
AWS-CIDR-BLOCK = ["0.0.0.0/0"]
